PegSolver.Mvc/Controllers/BoardController.cs
namespace PegSolver.Mvc.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using PegSolver.Mvc.Models;
    using PegSolver.Simple;

    public class BoardController : Controller
    {
        public ActionResult Index() {
            BoardViewModel bvm = this.BuildDefaultBoard();
            return View(bvm);
        }

        //[HttpGet]
        //[HttpPost]
        public ActionResult SolveBoard(string boardString) {
            string debugStr = boardString;
            Board board = new Board(boardString);
            IPegSolver pegSolver = this.CreateNewPegSolver();
            MoveStack moves = pegSolver.Solve(board);

            SolvedBoardViewModel solvedBoard = new SolvedBoardViewModel {
                OriginalBoard = board,
                MovesToSolve = moves,
            };

            return View(solvedBoard);
        }

        private BoardViewModel BuildDefaultBoard() {
            return new BoardViewModel(new Board("00000;11000;11100;11110;11111"));
        }

        private IPegSolver CreateNewPegSolver() {
            IMoveFinder moveFinder = new MoveFinder();
            return new SimplePegSolver(moveFinder, new BoardEvaluator(moveFinder));
        }
    }
}

PegSolver.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.6.4.min.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/custom.css")" rel="stylesheet" type="text/css" />
    @RenderSection("header",false)
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>Peg Game</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Board")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

PegSolver.Mvc/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <b>@Context.User.Identity.Name</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}